### PR TITLE
cache and use-eslintrc are booleans

### PR DESCRIPTION
**Pull request by voger**
The options `--cache` and `--use-eslintrc` are recognized as `string` and they remain always true. This PR sets them as `boolean` so the yargs translates them properly..

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

**Comment by johnspackman** [comment]
Hi,

Thank you for your email - I am unavailable, returning on April 12th.  
 I will get back to you as soon as possible, but if you have an emergency support issue please describe your issue in detail in email and then send a text message to the mobile number you have for me.

Regards
John Spackman

**Comment by hkollmann** [comment]
The compiler is merged with the qooxdoo main project. Could you do the same in qooxdoo? Thanks!

**Review by hkollmann — APPROVED** [review]

**Comment by voger** [comment]
@hkollmann Sure. Does this mean that all the compiler pull requests should be directed to the qooxdoo main package?

**Comment by hkollmann** [comment]
Yes.

**Review by cboulanger — APPROVED** [review]

**Pull request merged**
