### PR TITLE
Implement install from tree hash

### PR DESCRIPTION
**Pull request by cboulanger**
Implements #350

### CODE REVIEW

**Comment by oetiker** [comment]
does this mean I can now use any tree-ish after the @ ? tag/branch/hash

**Comment by cboulanger** [comment]
so far, only "tree/" is recognized, but in principle this should can be done with path-like id if it can be differentiated from a version. maybe this is why it might make sense to require "v" as a version prefix for all releases, everything else would be "tree-ish"?

**Comment by cboulanger** [comment]
This line is differentiating "releases" from "non-releases", we could change it accordingly:
https://github.com/qooxdoo/qooxdoo-compiler/blob/0b6eabda22940e8067786f99fc5c568e348efaec/lib/qx/tool/cli/commands/contrib/Install.js#L127

**Comment by cboulanger** [comment]
Or we merge my code and then you change in a way that you think would be better? I have no particular preference here....

**Comment by cboulanger** [comment]
We also need tests and documentation, but I don't have more time than for what I've done this morning.

**Comment by oetiker** [comment]
https://stackoverflow.com/questions/4044368/what-does-tree-ish-mean-in-git

at least on the git cli client 'tree-ish' is a 'thing' so I would assume that if you put it in the right place that all would happen automatically without requir3ement on yourside to have special handling

**Comment by cboulanger** [comment]
I see (but don't fully grasp the details). As the current way allows to address any arbitrary state of the code, it is enough for my purposes. I am open for anything that would make it more flexible & more "git-ish", but I am afraid I cannot put the time into implementing it myself ATM. Sorry.

**Comment by cboulanger** [comment]
now it no longer depends on the "tree/" prefix, but you can use any path into the code tree. This requires naming releases with a "v" prefix. That's already a requirement but one that I thought could be relaxed.

**Comment by cboulanger** [comment]
Sorry, didn't run `npm test` so there is a regression. Fixing it right away...

**Comment by cboulanger** [comment]
In any case, I haven't added other "tree-ish" expressions than "tree/<hash>". Feel free to do that here: 

https://github.com/qooxdoo/qooxdoo-compiler/blob/0b39d79bf1c5efff02a0c7e9891e1c54116e730a/lib/qx/tool/cli/commands/contrib/Install.js#L402-418

**Pull request merged**
