### PR TITLE
Link the "documentation" link on the `qx serve` landing page to the documentation folder in the framework

### PR DESCRIPTION
**Pull request by cboulanger**

### CODE REVIEW

**Comment by cboulanger** [comment]
@hkollmann You mean [here](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/resource/qx/tool/cli/serve/src/index.html)?

**Comment by hkollmann** [comment]
Found in partials/footer.html.

**Comment by cboulanger** [comment]
Fixed the links in the `src` folder also. 

I also added a  `--show-startpage` / `-S` parameter to `qx serve` so that the documentation link can be accessed even if there is only one application.

**Comment by cboulanger** [comment]
@johnspackman, can you have a look?

**Comment by johnspackman** [comment]
merging, thank you @cboulanger !

**Pull request merged**
