### PR TITLE
add qx test

### PR DESCRIPTION
**Pull request by hkollmann**
This adds qx test to the compiler.

To use qx test you need to add a test contrib to your app, e.g. testtapper.

Idea:
qx serve fires a new event after server start. qx test listen for this event and fires an event runTests. 
After this the process is finished.

The test contrib has to register a event handler to runTests in his compile.js file.
This event handler has to return a promise which is resolved after all tests are done.

See testtapper contrib for an example.

### CODE REVIEW

**Comment by cboulanger** [comment]
So the idea is that this class works like `qx serve`, with the only addition that it fires an event which the testing package can react to?

**Comment by hkollmann** [comment]
it starts serve, run all tests and terminate the process after this.

**Comment by hkollmann** [comment]
` process: async function() { 
      this.addListener("started", async () =>  { 
        let result = {errorCode: 0}; 
        let res = this.fireDataEvent("runTests", result); 
        res.then(() => { 
          process.exit(result.errorCode);           
        }); 
     }); 
      await this.base(arguments);`

**Comment by cboulanger** [comment]
But what I mean is that it doesn't really run any tests by itself - it just signals to a test runner that *might* exist that it should start the tests, no? So if there is no test runner, nothing happens. Is there a way for the command know if a test runner has been loaded at all, and throw an error if not?

**Comment by hkollmann** [comment]
Can we check if there are registered listeners to an event? If not no test runner is registered.

**Comment by hkollmann** [comment]
Found it: http://www.qooxdoo.org/devel/api/#qx.core.MEvent~hasListener!method_public, hasListener

**Comment by cboulanger** [comment]
Yes, that seems to be an pragmatic and efficient way - I was thinking of checking the installed packages, but this is much easier and completely sufficient!

**Comment by cboulanger** [comment]
So you can check for registered listeners and inform the user that s/he has to to install a test runner if no such listener has been found.

**Comment by cboulanger** [comment]
I was looking at the testtapper package but could not find the place where it listens to the `runTests` event - do you have merged your changes there yet?

**Comment by cboulanger** [comment]
How does `qx test` relate to the "qxl.testrunner" package?

**Comment by cboulanger** [comment]
Merged, thank you @hkollmann !

**Pull request merged**
