### PR TITLE
Fix js compile

### PR DESCRIPTION
**Pull request by johnspackman**

### CODE REVIEW

**Comment by hkollmann** [comment]
Could you try to compile the https://github.com/qooxdoo/qxl.apiviewer with this? It uses compile,json excessive.

**Comment by johnspackman** [comment]
done; there were some changes needed, I've pushed a fix for the API viewer

**Comment by hkollmann** [comment]
Then the demobrowser https://github.com/qooxdoo/qxl.demobrowser will not compile and longer either

Von meinem iPhone gesendet

**Comment by hkollmann** [comment]
When we have inputdata in the global scope we can remove it from the call to the function. 
This change breaks all compile.js - so we can remove Double data 

Von meinem iPhone gesendet

**Comment by johnspackman** [comment]
sorry, i broke that rebase ...

**Pull request closed without merging**
