### PR TITLE
Fixes #294

### LINKED ISSUE #294: Rename output folders in templates
As per the discussion on Gitter, the names of the output folders in the templates should be changed from `(source|build)-output` to `compiled/(source|build)`.

### PR DESCRIPTION
**Pull request by cboulanger**
This also updates (and radically simplifies) the .gitignore files

### CODE REVIEW

**Comment by cboulanger** [comment]
Sorry, forgot to fix the tests.

**Comment by cboulanger** [comment]
@hkollmann Can you test if it works on windows?

**Comment by hkollmann** [comment]
> @hkollmann Can you test if it works on windows?

It's working!

**Comment by johnspackman** [comment]
merging, thank you @cboulanger !

**Pull request merged**
