### PR TITLE
fixes https://github.com/qooxdoo/qooxdoo-compiler/issues/56, caused by missing babel polyfill

### PR DESCRIPTION
**Pull request by johnspackman**

### CODE REVIEW

**Comment by cboulanger** [comment]
Why does the test fail with `rake failed`? Doesn't seem anything to do with our code...

**Comment by hkollmann** [comment]
I think because travis is not configured. And then it uses the default configuration. Can we ignore this?

**Comment by hkollmann** [comment]
Yes we can. Merge is allowed.

**Comment by cboulanger** [comment]
But shouldn't we fix this first? It's probably not difficult since the tests used to pass, didn't they @johnspackman ?

**Comment by cajus** [comment]
I've already prepared a PR that includes travis and npm support for this repo. Looks like @oetiker didn't tick the checkbox for "only run if .travis.yml is present".

**Comment by cajus** [comment]
Currently the PR fails in travis, because 'npmt test' fails. See https://travis-ci.org/cajus/qooxdoo-compiler

**Comment by cajus** [comment]
Just fixed the travis settings.

**Comment by hkollmann** [comment]
Thanks  @johnspackman!

**Pull request merged**
