### PR TITLE
DO NOT MERGE YET: Updating gitignores of skeletons

### PR DESCRIPTION
**Pull request by cboulanger**
Any other files that should be put into the skeletons' `.gitignore` files?

### CODE REVIEW

**Comment by hkollmann** [comment]
db.json  and resource-db.json are changed during build - imho they should stay in the .gitignore

**Comment by cboulanger** [comment]
But they are contained in the `*-output` - folders anyways, aren't they? So stating them seems redundant. Or did I overlook something?

**Comment by hkollmann** [comment]
You are right..

**Comment by cboulanger** [comment]
Closing because issue is already taken care of.

**Pull request closed without merging**
