### PR TITLE
Fix install mess

### PR DESCRIPTION
**Pull request by hkollmann**
- move postinstall to prepare. So update will run only during npm install
- add prepack script to bind framework version to compiler
- fix some issues in deploy_npm
- add .npmignore. The .travis folder should not be part of the npm package
- run npm shrinkwrap to get actual shrinkwrap file
- remove git dependency

### CODE REVIEW

**Comment by hkollmann** [comment]
As i promised, here is a replace for https://github.com/qooxdoo/qooxdoo-compiler/pull/458.
This should adress both problems. Have a stable package and update framework during install from GitHub and pack for npm.

**Comment by oetiker** [comment]
@hkollmann my npm foo is weak, so I can not tell from the code ... BUT will the compiler be tested WITH the latest qooxdoo version already in place?

**Comment by hkollmann** [comment]
Good hint. Just tested npm link. prepare runs during link process - and test script runs npm link. So Framework will be updated before test

**Comment by hkollmann** [comment]
Here is the link for npm scripts: https://docs.npmjs.com/misc/scripts

**Comment by johnspackman** [comment]
is this ready for merge?  @oetiker please can you confirm that your question is answered?

**Pull request merged**
