### PR TITLE
APIfy website generation

### PR DESCRIPTION
**Pull request by cboulanger**
In preparation of #452 , this moves the build scripts for the local website into the `qx.tool.utils.Website class` to make them callable from the CLI code.

### CODE REVIEW

**Comment by cboulanger** [comment]
This removes the `qx/source/resource/website/build` folder and builds the local website on demand the first time it is used. It can be rebuilt using the `qx serve -R` option. Once @hkollmann adds statically the built qxl.* apps to the NPM package, we can switch to linking to them from the local web page.

**Comment by cboulanger** [comment]
@johnspackman can you elaborate?

**Comment by hkollmann** [comment]
Great! We should think About if if use the builder construction for all commands. But not in this PR.

**Comment by cboulanger** [comment]
@hkollmann You're right, for example `-v`/`--verbose` should be inherited rather than repeated in each builder... can you put this into a separate issue?

**Comment by johnspackman** [comment]
> @johnspackman can you elaborate?

if the compiler version number changes, the compiler will delete the output directory before starting the compile (that link to the Maker class was to illustrate where).  IMHO a similar detection for the compilation, when the version number changes it gets recompiled.

OTOH, unless there is a need to compile it with a user's project code, I don 't understand why this does not remain part of the deployment of new qx versions.

**Comment by cboulanger** [comment]
@johnspackman The reason I removed the build was that 1) it seemed strange to me to change the same things at two places: in the source and the build version, and 2) that I thought that it would be good to be able to dynamically change the local website based on specific configurations (for example, to link to locally built playground versus the one on the qooxdoo website). Since then, @hkollmann has rightly suggested that it makes more sense to include those apps pre-built in the NPM package - and I think that applies to the local website as well. Would you support this solution - to make website building part of the NPM deployment?

**Comment by johnspackman** [comment]
@cboulanger yes, I think inclusion in the npm deployment is ideal

**Comment by johnspackman** [comment]
merging, thank you @cboulanger

**Pull request merged**
