### PR TITLE
Compiler fixes

### PR DESCRIPTION
**Pull request by johnspackman**

### CODE REVIEW

**Comment by hkollmann** [comment]
I would prefer my solution for #514 because your solution did not fix the problem of missing libs during lint.

**Comment by johnspackman** [comment]
yes, I agree - i'll rebase once your PR is fixed

**Comment by johnspackman** [comment]
This PR now incorporates https://github.com/qooxdoo/qooxdoo-compiler/pull/515

**Comment by hkollmann** [comment]
You delete all the testdata stuff - but now the tests are not running  anymore?

**Pull request merged**
