### PR TITLE
in #325 oetiker removed the trailing / in loader-browser.tmpl.js to g…

### PR DESCRIPTION
**Pull request by hkollmann**
…et rid of //. No it's necesarry to append / to resource.

### CODE REVIEW

**Comment by cboulanger** [comment]
Maybe instead of removing the slash, it would be better to add a `.replace(/\/\//,"/")` where necessary.

**Comment by johnspackman** [comment]
merging, thank you @hkollmann !

**Comment by oetiker** [comment]
note that I did NOT mess with the resources path:

https://github.com/qooxdoo/qooxdoo-compiler/pull/325/files?utf8=%E2%9C%93&diff=unified&w=1#diff-48adb84e3faed9722c679affa66153fdL59

I think there are probably more problems ahead ... I did some experiments, but found that I ended up with double slashes in resources paths!

**Comment by johnspackman** [comment]
@hkollmann do you have an example of why you needed to add the trailing '/' in?  I've just tried this and it looks that resourceUri does not need to have a trailing "/" because `qx.util.ResourceManager.toUri` always adds one

**Comment by hkollmann** [comment]
Yes, i have. Just an example with 

  "externalResources": {
    "script": [
      "js/zip.js"
    ]
  }
[test.zip](https://github.com/qooxdoo/qooxdoo-compiler/files/2947450/test.zip)


Running gives:  Cannot load script test/../resourcejs/zip.js

**Comment by zaucker** [comment]
See also my example in the chat.

**Pull request merged**
