### PR TITLE
adds console colorisation

### PR DESCRIPTION
**Pull request by johnspackman**
allows the default color for console output to be set with (eg) `qx config set qx.default.color 'white bgRed bold'`

default value for --no-feedback is set with `qx config set qx.default.feedback false` (if not specified, default remains "on" as before)

### CODE REVIEW

**Comment by cboulanger** [comment]
es-lint is not nice to you, it seems 😄  But probably `qx lint --fix` should help.

**Comment by johnspackman** [comment]
oops, one day i'll remember to run lint before i commit! :)

**Comment by derrell** [comment]
Just saw this. Can you confirm that color can be turned off entirely in a config file? Color doesn't work in some environments, yielding instead a bunch of control characters visible on the screen...

**Comment by johnspackman** [comment]
yes - the colours only apply if turned on via the config setting, otherwise they are as before.  

However, the feedback option (which is on unless `--no-feedback` is given or `qx.default.feedback` is set to false) will use ANSI sequences including colour - this is also as before, but I imagine that these would cause the same issues as colour?

**Comment by derrell** [comment]
Yes, that would cause the same problem. IMO, either it should look at your TERM environment variable and determine that you have color available or are an ANSI-compatible "terminal" type, or not use coloring unless specifically asked to.

**Comment by johnspackman** [comment]
It should do - I've used the [console-control-strings](https://www.npmjs.com/package/console-control-strings) npm module because that's the same module which the gas gauge module uses for all the pretty termcap-esque progress bar

**Pull request merged**
