### PR TITLE
the authors key is an array ...

### PR DESCRIPTION
**Pull request by oetiker**

### CODE REVIEW

**Comment by cboulanger** [comment]
eslint is complaining about one-liners in the code. 
Off-topic here but does this rule make sense?

**Comment by hkollmann** [comment]
@cboulanger : With function closed {} yes - it's more readable.

**Comment by cboulanger** [comment]
Doesn’t qx lint --fix help?

**Comment by hkollmann** [comment]
Before run qx lint --fix you must run:
qx pkg update
qx pkg install

**Comment by cboulanger** [comment]
Merged, thank you @oetiker !

**Pull request merged**
