### PR TITLE
READY FOR REVIEW: Rename contrib to packages

### PR DESCRIPTION
**Pull request by cboulanger**
Implements #369.

This removes all references to "contrib" from the compiler code and the documentation, apart from deprecation notices and the URL of the `qooxdoo/qx-contrib` repository. 

The implementation automatically migrates a few files, making the code backwards-incompatible, i.e.
the code won't work with an earlier compiler version:
- the `contrib` dir is renamed to `packages`
- `contrib.json` is renamed to `qx-lock.json`
- `contrib-cache.json` is renamed to `packages-cache.json`

On first use of a `qx package|contrib` command, the CLI checks if a package needs to be migrated. If yes, `qx package migrate` is called, which implicitly calls `qx package upgrade --reinstall`, which fixes the paths in the lockfile. The migration command 
- automatically corrects the entry for the download cache dir in `.gitignore`,
- fixes the paths in the lock file, and
- updates the dependencies in Manifest.json/requires

### CODE REVIEW

**Comment by hkollmann** [comment]
Is it possible to use pkg as an alias for package?

**Comment by cboulanger** [comment]
@hkollmann will fix typo and put in an alias. 

@hkollmann @johnspackman Should I name the download cache dir `qx-packages` instead of `packages`? On second thought, `packages` seems a bit too generic as name...

**Comment by cboulanger** [comment]
Don't merge yet, I have another commit in the works.

**Comment by cboulanger** [comment]
The last commits were a bit chaotic because of a merge conflict with the shrink-wrap file. 

Now we have a migration that works async (which requires a bit of heavy refactoring) and will also update the `.gitignore` file (could do others as well).

**Comment by cboulanger** [comment]
Last commit of the day: now the migration automatically fixes the paths in the lock file. What we still need is an automatic update of the required version of the compiler, since the project state after migration is incompatible with earlier versions.

**Comment by cboulanger** [comment]
@johnspackman @hkollmann Given that this PR is backwards-compatible to existing code, but produces backwards-incompatible user code, I now think I should rebase it on @hkollmann’s PR and apply the changes to the new scoped NPM packages only. What do you think?

**Comment by johnspackman** [comment]
@cboulanger re rebasing: that could be a good plan, so that the old `qxcompiler` package doesn't have ay major changes immediately before becoming deprecated.  Which means it would be good to create a branch from the last qxcompiler release with a final change that warns that it is deprecated and the name change

**Comment by johnspackman** [comment]
merging, thank you @cboulanger !

**Comment by johnspackman** [comment]
I just realised that "package" is a reserved word in ES5, does this make it illegal to have `qx.tool.cli.commands.package`?  Perhaps rename to `qx.tool.cli.commands.packages`?

**Comment by cboulanger** [comment]
It's not a problem for object properties: https://stackoverflow.com/a/17911822

**Pull request merged**
