### PR TITLE
fixes https://github.com/qooxdoo/qooxdoo-compiler/issues/440

### PR DESCRIPTION
**Pull request by johnspackman**
In the original request in https://github.com/qooxdoo/qooxdoo-compiler/issues/440#issuecomment-499993805, @derrell asked for things like missing class references to also trigger a non-zero exit status - this has kind of been done, but missing references are "just" unresolved symbols which are just warnings.  As they're warnings, they don't stop the class from being compiled, so even if a non-zero exit status was given, the next time you ran `qx compile` you'd get a zero exit status.

IMHO it's a pain anyway if warnings are only displayed if a class is compiled - ie if the class is not edited, you don't see the warning even if that warning could affect code you *are* editing.

As well as non-zero exit codes, this PR also displays warnings for classes that have not been compiled, and also the `--warn-as-error` argument will cause a non-zero exit code if there are any warnings.

Although this is not quite as exact as detecting a missing class, my thought is that as this may have the same net effect.

### CODE REVIEW

**Comment by derrell** [comment]
That sounds like it should allow accomplishing the goal: ensure that any `qx compile`-detected error or warning stops further steps in a scripted build process. Thanks!

**Comment by oetiker** [comment]
does this the also cause the compiler to set an exit value on syntax error ?

**Comment by johnspackman** [comment]
yes

**Comment by cboulanger** [comment]
@hkollmann yargs will translate "warn-es-error" to "warnAsError" implicitly (since hyphens cannot be used as member names unless in quotes and square brackets)

**Comment by johnspackman** [comment]
@hkollmann also AIUI if you tell yargs the name is `warn-as-error` you can use `--warn-as-error` or `--warnAsError`, and reference it as `argv["warn-as-error"]` or `argv["warnAsError"]`.  But (I think) that if you tell yargs the name is `warnAsError` then only `--warnAsError` works and only `argv["warnAsError"]` in the code

**Comment by johnspackman** [comment]
thanks for patching this @hkollmann 👍

**Pull request merged**
